version: "3"

services:
  tcp:
    build:
      context: tcp
      dockerfile: Dockerfile
    ports:
      - "39674:28563"
  ws:
    build:
      context: ws
      dockerfile: Dockerfile
    ports:
      - "28563:28563"
